/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSportsRouteImport } from './routes/work.sports'
import { Route as WorkInfrastructureRouteImport } from './routes/work.infrastructure'
import { Route as WorkHealthcareRouteImport } from './routes/work.healthcare'
import { Route as WorkEducationRouteImport } from './routes/work.education'
import { Route as WorkDisasterResponseRouteImport } from './routes/work.disaster-response'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkSportsRoute = WorkSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => WorkRoute,
} as any)
const WorkInfrastructureRoute = WorkInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => WorkRoute,
} as any)
const WorkHealthcareRoute = WorkHealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => WorkRoute,
} as any)
const WorkEducationRoute = WorkEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => WorkRoute,
} as any)
const WorkDisasterResponseRoute = WorkDisasterResponseRouteImport.update({
  id: '/disaster-response',
  path: '/disaster-response',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impact': typeof ImpactRoute
  '/work': typeof WorkRouteWithChildren
  '/work/disaster-response': typeof WorkDisasterResponseRoute
  '/work/education': typeof WorkEducationRoute
  '/work/healthcare': typeof WorkHealthcareRoute
  '/work/infrastructure': typeof WorkInfrastructureRoute
  '/work/sports': typeof WorkSportsRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impact': typeof ImpactRoute
  '/work/disaster-response': typeof WorkDisasterResponseRoute
  '/work/education': typeof WorkEducationRoute
  '/work/healthcare': typeof WorkHealthcareRoute
  '/work/infrastructure': typeof WorkInfrastructureRoute
  '/work/sports': typeof WorkSportsRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impact': typeof ImpactRoute
  '/work': typeof WorkRouteWithChildren
  '/work/disaster-response': typeof WorkDisasterResponseRoute
  '/work/education': typeof WorkEducationRoute
  '/work/healthcare': typeof WorkHealthcareRoute
  '/work/infrastructure': typeof WorkInfrastructureRoute
  '/work/sports': typeof WorkSportsRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/impact'
    | '/work'
    | '/work/disaster-response'
    | '/work/education'
    | '/work/healthcare'
    | '/work/infrastructure'
    | '/work/sports'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/impact'
    | '/work/disaster-response'
    | '/work/education'
    | '/work/healthcare'
    | '/work/infrastructure'
    | '/work/sports'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/impact'
    | '/work'
    | '/work/disaster-response'
    | '/work/education'
    | '/work/healthcare'
    | '/work/infrastructure'
    | '/work/sports'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ImpactRoute: typeof ImpactRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/sports': {
      id: '/work/sports'
      path: '/sports'
      fullPath: '/work/sports'
      preLoaderRoute: typeof WorkSportsRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/infrastructure': {
      id: '/work/infrastructure'
      path: '/infrastructure'
      fullPath: '/work/infrastructure'
      preLoaderRoute: typeof WorkInfrastructureRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/healthcare': {
      id: '/work/healthcare'
      path: '/healthcare'
      fullPath: '/work/healthcare'
      preLoaderRoute: typeof WorkHealthcareRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/education': {
      id: '/work/education'
      path: '/education'
      fullPath: '/work/education'
      preLoaderRoute: typeof WorkEducationRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/disaster-response': {
      id: '/work/disaster-response'
      path: '/disaster-response'
      fullPath: '/work/disaster-response'
      preLoaderRoute: typeof WorkDisasterResponseRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkDisasterResponseRoute: typeof WorkDisasterResponseRoute
  WorkEducationRoute: typeof WorkEducationRoute
  WorkHealthcareRoute: typeof WorkHealthcareRoute
  WorkInfrastructureRoute: typeof WorkInfrastructureRoute
  WorkSportsRoute: typeof WorkSportsRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkDisasterResponseRoute: WorkDisasterResponseRoute,
  WorkEducationRoute: WorkEducationRoute,
  WorkHealthcareRoute: WorkHealthcareRoute,
  WorkInfrastructureRoute: WorkInfrastructureRoute,
  WorkSportsRoute: WorkSportsRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ImpactRoute: ImpactRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
